name: RebornMySQLInventories
main: net.craftersland.bridge.inventory.Inv
version: 2.5.0
author: Brunyman (Original) | Reborn Community (1.21) by alexcuadroo
website: https://github.com/brunyman/InventoryBridge
load: STARTUP
api-version: 1.21
description: Sincroniza inventarios de jugadores entre múltiples servidores usando MySQL.
softdepend: [ProtocolLib]